name: Deploy to Google Apps Script

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          cd media_commons_booking_app
          npm ci

      - name: Deploy to Google Apps Script
        run: |
          cd media_commons_booking_app
          echo "$CLASP_CREDENTIALS" > .clasprc.json
          npx clasp push
        env:
          CLASP_CREDENTIALS: ${{ secrets.CLASP_CREDENTIALS }}
